import = [
	'~/.config/alacritty/themes/themes/gruvbox_dark.toml'
]

live_config_reload = true
shell.args = ["new", "-A", "-s", "root"]
shell.program = "/opt/homebrew/bin/tmux"

[window]
dimensions.lines = 30
dimensions.columns = 80

padding.x = 3
padding.y = 0
dynamic_padding = false

title = ":)"
dynamic_title = true

[font]
size = 10

normal.style = "Regular"
normal.family = "JetBrainsMono Nerd Font"

[mouse]
hide_when_typing = true

