import = [
	'~/.config/alacritty/base16/colors/base16-black-metal-nile.toml'
]

live_config_reload = true
shell.args = ["new", "-A", "-s", "root"]
shell.program = "/opt/homebrew/bin/tmux"

[window]
dimensions.lines = 30
dimensions.columns = 80

padding.x = 3
padding.y = 0
dynamic_padding = false

title = ":)"
decorations = "None"
dynamic_title = true

[font]
size = 10

normal.style = "Regular"
normal.family = "Hasklug Nerd Font"

bold.style = "SemiBold"
bold_italic.style = "SemiBold Italic"

[mouse]
hide_when_typing = true

